all: html

SPHINX_PROJECT_NAME = TiWi-SL Simple Webserver Demo Quickstart Guide
VERSION = 1v0
SOURCE_INCLUDE_DIRS = ../../app_tiwisl_simple_webserver
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
